var text = document.getElementById('text');
var values = document.getElementsByClassName('value');
var arr =[  "Rolls-Royce Motor Cars is a subsidiary  of BMW and is known for its opulent and handcrafted luxury cars. The companys vehicles are celebrated for their impeccable craftsmanship, attention to detail, and cutting-edge technology. Some of their most famous car models include the Phantom, Ghost, Wraith, and Dawn. Rolls-Royce cars often feature powerful engines, a comfortable and luxurious interior, and customizable options that allow customers to create a truly unique vehicle.It seems like youre asking about Rolls-Royce the British luxury automobile and aerospace company. Rolls-Royce is renowned for producing high-end luxury cars, as well as being a significant player in the aerospace and defense industries. Heres some information about both aspects of the company Rolls-Royce Holdings plc is a separate entity from Rolls-Royce Motor Cars and is primarily involved in the aerospace, defense, and power systems sectors. They are a global leader in designing, manufacturing, and maintaining engines for various applications, including commercial and military aircraft, naval vessels, and power generation systems. Rolls-Royce engines are used by many airlines and military organizations around the world.The company has a long history dating back to 1904 when Charles Rolls and Henry Royce founded it. Over the years, Rolls-Royce has built a reputation for engineering excellence, innovation, and reliability. The brands commitment to quality and luxury has helped it maintain its prestigious status in both the automotive and aerospace industries.Please note that my knowledge is based on information available up until September 2021, and there may have been developments or changes in the company since then.Rolls-Royce is a British company known for crafting luxury automobiles of unparalleled quality and for being a prominent player in the aerospace and defense industries.",
            "HTML serves as the backbone of web content , providing the structural foundation for web pages. It employs a system of elements and tags to define the layout and organization of content. Elements like headings, paragraphs, lists, images, and links are used to structure information logically. HTML acts as a framework, allowing developers to create a hierarchy of content that browsers render appropriately. By utilizing semantic HTML elements, developers can enhance accessibility and improve search engine optimization.CSS complements HTML by adding style and design to web pages. It separates content from presentation, allowing developers to define visual attributes such as colors, fonts, layouts, and spacing. CSS employs selectors to target specific HTML elements and apply styles to them. This separation of concerns enhances maintainability and allows for consistent design across a website. Modern CSS features, like flexbox and grid layouts, empower developers to create responsive and dynamic designs that adapt to various screen sizes JavaScript is a versatile programming language that introduces interactivity and dynamic behavior to web pages. It enables developers to create responsive and interactive user experiences by manipulating the Document Object Model DOM – the representation of a webpages structure in the browser. With JavaScript, developers can build features like form validation, animations, real-time updates, and complex user interfaces. Moreover, JavaScript is often used to fetch data from servers and update web content without requiring a full page reload, enhancing performance and user satisfaction.These three technologies work harmoniously to create cohesive and engaging web experiences. HTML, CSS, and JavaScript are typically used together to build modern websites and web applications. Developers utilize HTML to structure content, CSS to style it attractively, and JavaScript to add functionality and interactivity. This combination allows for the creation of feature-rich websites that cater to users needs in terms of aesthetics and usability.",
            "India, the seventh-largest country in the world, is a land of unparalleled diversity, culture, and heritage. With a rich history that spans thousands of years, Indias influence on global civilization is undeniable. From its ancient civilizations to its modern technological advancements, India continues to captivate the worlds attention. Geographically, India encompasses a wide range of landscapes. From the towering Himalayan mountain range in the north to the vast Thar Desert in the west, and from the fertile Gangetic plains to the lush Western Ghats and the pristine coastal regions, Indias topography is a testament to natures diversity. This geographical variation has not only shaped Indias climate but also influenced its flora, fauna, and way of life. Indias cultural tapestry is woven from the threads of its diverse population. With over a billion people, the country is a mosaic of languages, religions, and traditions. Hinduism, Buddhism, Islam, Sikhism, Christianity, and countless other faiths coexist harmoniously, contributing to a unique spiritual landscape. Festivals like Diwali, Eid, Christmas, and Holi are celebrated with fervor, uniting people in the spirit of shared joy.The Indian subcontinent has been a cradle of civilization for millennia. Indus Valley Civilization, one of the worlds oldest urban cultures, flourished here. Throughout its history, India has witnessed the rise and fall of mighty empires, such as the Maurya, Gupta, Mughal, and British Empires. These civilizations have left an indelible mark on Indias architecture, art, and societal norms. Magnificent monuments like the Taj Mahal, Qutub Minar, and Ajanta Caves are living testaments to Indias architectural prowess.Cultural heritage is also embedded in Indias classical arts. Indian classical music, with its intricate melodies and rhythms, and classical dance forms like Bharatanatyam, Kathak, and Odissi, express emotions and stories that have been passed down through generations. Literature, too, has thrived, with ancient epics like the Mahabharata and Ramayana laying the",
            "The lion, scientifically known as Panthera leo, is a captivating and iconic creature that has captured human fascination for centuries. With its powerful presence, distinct appearance, and cultural significance, the lion holds a unique place both in the natural world and in human narratives.The physical traits and behaviors of lions are as captivating as they are intriguing. These magnificent creatures are part of the big cat family, featuring a distinctive golden-brown coat that defines their regal appearance. One of the most recognizable characteristics of male lions is their magnificent manes, varying in color from blond to black. These manes contribute to their aura of strength and dominance. Lionesses, the female counterparts, do not possess manes, but their role in the pride is equally vital.Lions are known for their social behavior and live in groups called prides. These prides typically consist of related females, their offspring, and a few dominant males. This cooperative structure contributes to hunting success, protection of the young, and overall survival of the species. Lions are notable for their powerful roars, which serve as a form of communication, asserting territorial claims and sending messages to others.In terms of habitat and distribution, lions once roamed diverse regions around the world. However, habitat loss, hunting, and human conflicts have significantly restricted their range. Today, wild lions primarily inhabit sub-Saharan Africa, favoring savannas, grasslands, and open woodlands as their domains. A small population also resides in Indias Gir Forest National Park. The lions cultural and symbolic significance is deeply ingrained in human history. Throughout various societies, lions have embodied traits such as courage, strength, and leadership. They have featured prominently in religious texts, mythologies, and heraldic imagery. The lions image has been employed to represent power and authority, gracing coats of arms, national flags, and sculptures. The ancient Egyptian Sphinx, with its lions body and human head, epitomized wisdom and strength.",
            "The rose flower, known by its scientific name Rosa, stands as a timeless symbol of beauty, love, and elegance. With its exquisite petals, enchanting fragrance, and universal appeal, the rose has held a special place in human culture and natures bounty.The roses physical characteristics are a testament to its allure. Its lush, velvety petals come in a spectrum of colors, from vibrant reds and pinks to delicate whites and yellows. The various hues express diverse emotions, from passion to purity. The arrangement of these petals creates a captivating form that has inspired artists, poets, and admirers throughout history.Beyond its visual charm, the roses fragrance is equally captivating. The delicate scent wafting from the petals evokes feelings of calm, nostalgia, and romance. For centuries, perfumers and artists have sought to capture this essence, creating fragrances, oils, and artworks that mirror the roses intoxicating aroma.The roses symbolism transcends its aesthetic appeal. Across cultures and generations, it has represented love, passion, and devotion. It has been gifted on occasions of celebration, adorning weddings, anniversaries, and other significant milestones. Yet, the roses symbolism extends beyond love it embodies broader themes such as beauty, lifes transient nature, and the interconnectedness of all living things.In the realm of literature, the rose has held a profound place. Poets and writers have woven its symbolism into their works, crafting metaphors and allegories that reflect the human experience. From Shakespeare to Rumi, the rose has inspired verses that resonate with emotions and truths.Culturally, the rose has played a pivotal role. In religious contexts, it has been linked to spirituality, often symbolizing purity and divinity. In art, it has adorned paintings, sculptures, and textiles, adding a touch of grace and elegance to human creations. Additionally, its use in culinary endeavors, such as rose-flavored dishes and teas, underscores its versatility and appeal.However, the roses allure is not confined to its visual and symbolic aspects. It is a product of natures intricate design, each petal unfolding as a result of complex biological processes. From pollination to reproduction, the roses life cycle showcases the marvels of natures ingenuity.",
            "Colors hold a significant place in our lives, both in terms of aesthetics and psychological impact. Symbolizing the vastness of the sky and the serene expanse of the ocean, blue captures the essence of nature's grandeur and offers a plethora of interpretations across cultures and contexts.Blue, often associated with tranquility, invokes a sense of calmness and serenity. Gazing at the clear blue sky or the gentle ripples of a calm sea can instantly soothe the human mind, evoking a feeling of peace and reprieve from the chaos of daily life. This calming effect of blue has been harnessed in various aspects of human existence, from interior design to therapeutic practices, where shades of blue are utilized to create spaces of relaxation and meditation.Yet, blue is far from being just a tranquil hue. Its range of shades encompasses a spectrum of emotions and moods. A darker shade of blue can evoke feelings of depth, wisdom, and introspection. This depth is mirrored in the nighttime sky, where celestial bodies like stars and planets twinkle against a dark blue canvas, inviting the human imagination to explore the mysteries of the cosmos. The contrast between the light and dark shades of blue symbolizes the duality of life - the interplay between moments of clarity and moments of contemplation.Blue's versatility extends beyond nature and into the cultural realm. Across different societies, blue often carries distinct symbolic meanings. In many Western cultures, blue is linked to notions of loyalty and trust, often symbolizing dependability and reliability. In contrast, some Eastern cultures associate blue with spirituality and divinity, a color that represents higher ideals and inner peace. The fact that blue can evoke such diverse sentiments speaks to its power to communicate across cultural boundaries.Art and creativity have been profoundly influenced by blue throughout history. From the indigo-dyed textiles of ancient civilizations to the ethereal blue hues in Renaissance paintings, artists have harnessed the color to evoke emotions and weave narratives. The iconic works of Vincent van Gogh and Pablo Picasso, among others, stand as testament to blue's ability to convey both melancholy and vibrancy, enabling artists to express complex emotions and ideas that might otherwise be challenging to articulate."
]
text.innerText = arr[Math.floor(Math.random()*6)];
var inText = text.innerText;
var total =0, wrong = 0, correct = 0,sec = 0, min = 0;
setInterval(
    function(){
        sec++;
        if(sec == 60){
            min++;
            sec = 0;
        }
        values[4].innerHTML = `<h3>${min}: ${sec}</h3>`;
    },1000
);
document.addEventListener('keydown',(e)=>{
    // let innertext = inText;
    console.log(e);
    let dum =   event.key === 'Shift' || event.key === 'CapsLock' || event.key === 'Enter' || 
                event.key === 'Tab' || event.key === 'Control'|| event.key === 'Meta' || 
                event.key === 'NumLock' || event.key === 'Alt' ||
                event.key === 'Escape'
    if(event.keyCode === 32)e.preventDefault();
    if(!dum){
        if(inText === '')
            alert(`Game over`)
        let char = inText.charAt(0);
        var space = ""
        if(inText.length >= 2 && inText.charAt(1) === ' ')
            space = "_"
        let ev = event.key === char;
        if(ev){
            correct++;
            values[1].innerHTML = `<h3>${correct}</h3>`
            // if(char === '')
            text.innerHTML = space+inText.slice(1,inText.length);
            // else
                // text.innerHTML = inText.slice(1,inText.length);
            inText = inText.slice(1,inText.length);
        }
        else{
            wrong++;
            values[0].innerHTML = `<h3>${wrong}</h3>`
        }
        total++;
        values[2].innerHTML = `<h3>${total}</h3>`
        values[3].innerHTML = `<h3>${Math.floor(correct/total*100)}%</h3>`
    }
})